<a href="https://colab.research.google.com/github/sukukumaresan2006-blip/Data-Analytics-using-Python-Project/blob/main/day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy

In [1]:
import numpy as np

marks=np.array([98,85,78,92])

print(marks)

[98 85 78 92]


In [2]:
import numpy as np

students=np.array([
    [90,85],
    [78,92],
    [88,95]
])

print(students)

[[90 85]
 [78 92]
 [88 95]]


In [3]:
import numpy as np
arr=np.zeros((2,3))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


Indexing & Slicing

In [4]:
import numpy as np

marks=np.array([90,85,78,92])

print(marks[2])

78


In [5]:
import numpy as np

marks=np.array([90,85,78,92,88])

print(marks[1:4])

[85 78 92]


Average Calclator

In [6]:
def calculate_average(a, b, c):
    return (a + b + c) / 3

try:
    a = int(input("Enter 1st number: "))
    b = int(input("Enter 2nd number: "))
    c = int(input("Enter 3rd number: "))

    print("calculate_average =", calculate_average(a, b, c))

except ValueError:
    print("Invalid Input")

Enter 1st number: 70
Enter 2nd number: 80
Enter 3rd number: 69
calculate_average = 73.0


Practice 1:Student score Analysis

In [7]:
scores=[78,85,92,67,88]

total=sum(scores)
average=total/len(scores)
highest=max(scores)
lowest=min(scores)

print("student scores:",scores)
print("total marks:",total)
print("average marks:",average)
print("highest mark:",highest)
print("lowest mark:",lowest)

student scores: [78, 85, 92, 67, 88]
total marks: 410
average marks: 82.0
highest mark: 92
lowest mark: 67


Practice 2:Sales Array Calculations

In [8]:
sales=[12000,15000,18000,14000,20000]

total_sales=sum(sales)
average_sales=total_sales/len(sales)
highest_sales=max(sales)
lowest_sales=min(sales)

print("monthly sales:",sales)
print("total sales:",total_sales)
print("average sales:",average_sales)
print("highest sales:",highest_sales)
print("lowest sales:",lowest_sales)

monthly sales: [12000, 15000, 18000, 14000, 20000]
total sales: 79000
average sales: 15800.0
highest sales: 20000
lowest sales: 12000
